### ISSUE TITLE
Some questions

### ISSUE THREAD

**Issue by hrqmonteiro** [tofutech/notamac#1]
1 - How did you put the "Finder" label on the mock global menu when you are on the desktop?
2 - How did you get the ' system preferences' icon left of the clock?

![Screenshot from 2022-08-03 11-06-30](https://user-images.githubusercontent.com/17055027/182628647-05df59b8-d396-4bf8-a683-805d5ad1d2d5.png)
![Screenshot from 2022-08-03 11-06-20](https://user-images.githubusercontent.com/17055027/182628655-bacd9ab5-eacb-49af-8bfd-26fa5f3668cd.png)

**Comment by Zany-Zachary1** [comment]
The UNITE extension allows custom text when desktop is selected.  It doesn't do anything, but it looks nice.  I made the mock menu and it pairs well with unite :)
